apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports: 
    - name: posts #can be anything, mainly kep as the file
      protocol:  TCP
      port: 4000 #For node port service 
      targetPort: 4000 # port for post service on the container
    